test-19.09:
  variables:
    NIX_PATH: nixpkgs=channel:nixos-19.09
    SKIP_TESTS: manylinux,preferWheel
  script:
    - nix-shell -p git --run "nix-build --no-out-link --show-trace tests"

test-unstable:
  variables:
    NIX_PATH: nixpkgs=channel:nixos-unstable
  script:
    - nix-shell -p git --run "nix-build --no-out-link --show-trace tests"

graphs:
  script:
    - nix-shell --run 'mkdir -p artifacts && cd artifacts && poetry2nix-flamegraph'
  artifacts:
    paths:
    - artifacts/

nixpkgs-fmt:
  script:
    - ./check-fmt
